class Tickers:
       ticker_json =  {
            "BTC-USD" : "BTC-USD",
            "0P0000XW51.BO": "Quant ELSS Tax Saver Fund MF",
            "0P00017844.BO": "Mirae Asset ELSS Tax Saver Fund MF",
            "0P00005VCS.BO": "HSBC ELSS Tax Saver Fund MF",
            "0P0000XVU7.BO": "Axis ELSS Tax Saver Fund MF",
            "0P0000XV1I.BO": "Bandhan ELSS Tax Saver Fund MF",
            "0P0001R64W.BO": "Motilal Oswal Nifty Microcap 250 Index Fund MF",
            "0P0000XVDP.BO": "Nippon India Growth Direct Growth MF",
            "0P0001RQX5.BO": "Zerodha Nifty LargeMidcap 250 Index Fund Tax Saver Dir Gr MF",
            "0P0000GB29.BO": "Aditya BSL ELSS Tax Saver Gr MF",
            "0P0000XW04.BO": "Canara Robeco ELSS Tax Saver Dir Gr MF",
            "0P00011MAX.BO": "Axis Small Cap Fund Dir Gr MF",
            "0P000159Q2.BO": "Motilal Oswal ELSS Tax Saver Reg Gr MF",
            "0P00009J3K.BO": "HDFC Mid-Cap Opportunities Gr MF",
            "0P0000XVFY.BO": "Nippon India Small Cap Dir Gr MF",
            "0P00008TPO.BO": "Kotak Emerging Equity Scheme MF",
            "0P0000XW1B.BO": "SBI Small Cap Fund Dir Gr MF",
            "0P0000XVUH.BO": "Axis Midcap Fund Dir Gr MF",
            "0P00012ALU.BO": "Motilal Oswal Midcap Reg Gr MF",
            "0P0000XW4X.BO": "Quant Small Cap Fund MF",
            "0P00012ALS.BO": "Motilal Oswal Midcap Dir Gr MF",
            "0P0000XW2T.BO": "DSP ELSS Tax Saver Dir Gr MF",
            "0P0000YK1E.BO": "ICICI Pru Thematic Advantage dir  MF",
            "0P0000XVXV.BO": "Aditya BSL Digital India Dir Gr MF",
            "0P0001BA2I.BO": "Edelweiss Mid Cap Fund MF",
            "0P0000IQJ7.BO": "Quant Flexi Cap Fund MF",
            "0P0000XW4V.BO": "Quant Mid Cap Dir Gr MF",
            "0P0000XVAA.BO": "HDFC Small Cap Dir Gr MF",
            "0P0000XUZ6.BO": "ICICI Pru Technology Dir Gr MF",
            "0P0000XV5R.BO": "Kotak Emerging Equity Dir Gr MF",
            "0P000093TC.BO": "Invesco India Mid Cap Gr MF",
            "0P0000XW4E.BO": "Quant Active Dir Gr MF",
            "0P0000YWL1.BO" : "Parag Parikh Long Term Equity Direct Growth MF",
            "0P0000XW8F.BO" : "HDFC Mid-Cap Opportunities Dir Gr MF",
            "0P0000XW24.BO" : "DSP Small Cap Dir Gr MF",
            "0P0000XV9V.BO" : "Mirae Asset Large & Midcap Dir Gr MF",
            "0P0000XVKP.BO" : "SBI Technology Opportunities Dir Gr MF",
            "0P0000XW5R.BO" : "Franklin India Technology Dir Gr MF",
            "0P0000XW4F.BO" : "Quant Large and Mid Cap Dir MF",
            "0P0000XVDP.BO" : "Nippon India Growth Dir Gr MF",
            "0P0000XW51.BO" : "Quant ELSS Tax Saver Dir Gr MF",
            "0P0000XVZR.BO" : "Bank of India ELSS Tax Saver Dir MF",
            "0P0001F5O4.BO" : "Bank of India Small Cap Dir Gr MF",
            "0P0001FKEE.BO" : "Canara Rob Small Cap Fund Dir Gr MF",
            "0P0001FI5D.BO"	: "Edelweiss Small Cap Fund Regular Growth MF",
            "0P0001EUZZ.BO" : "Tata Small Cap Fund Direct Growth MF",
            "0P0001F1DY.BO" : "Dsp Healthcare Fund Direct Growth MF",
            "0P0001EQU4.BO" : "Invesco India Smallcap Fund Dir Growth MF",
            "0P0001HZ17.BO" : "Parag Parikh ELSS Tax Saver Fund Fir G MF",

            "NIFTY50ADD.NS": "Nifty 50 Index",
            "SBIETFPB.NS": "Nifty Private Bank Index",
            "NIF5GETF.NS": "UTI Nifty 5 yr Benchmark G-Sec ETF",
            "MOGSEC.NS": "Nifty 5 yr Benchmark G-Sec Index",
            "NIF10GETF.NS": "UTI Nifty 10 yr Benchmark G-Sec ETF",
            "NV20IETF.NS": "Nifty50 Value 20",
            "SENSEXADD.NS": "DSP S&P BSE Sensex ETF",
            "TOP100CASE.NS": "Zerodha Nifty 100 ETF",
            "PVTBANKADD.NS": "DSP Nifty Private Bank ETF",
            "HDFCNIF100.NS": "HDFC NIFTY 100 ETF",
            "NV20BEES.NS": "Nifty50 Value20 TRI",
            "GSEC10IETF.NS": "ICICI Prudential Nifty 10 yr Benchmark G-Sec ETF",
            "BANKNIFTY1.NS": "Nifty Bank",
            "UNIONGOLD.NS": "Commodity Gold",
            "INFRAIETF.NS": "ICICI Prudential Nifty Infrastructure ETF",
            "HDFCPSUBK.NS": "HDFC NIFTY PSU BANK ETF",
            "GSEC5IETF.NS": "Nifty 5 yr Benchmark G-Sec Index",
            "LTGILTBEES.NS": "NIFTY 8-13 yr G-Sec Index",
            "AXISBPSETF.NS": "Nifty AAA Bond Plus SDL Apr 2026 50:50 Index",
            "GSEC10YEAR.NS": "Mirae Asset Nifty 8-13 yr G-Sec ETF",
            "LIQUIDCASE.NS": "Zerodha Nifty 1D Rate Liquid ETF",
            "GROWWLIQID.NS": "Nifty 1D Rate Index",
            "LIQUIDADD.NS": "DSP S&P BSE Liquid Rate ETF",
            "LIQUIDSHRI.NS": "SHRIRAM NIFTY 1D RATE LIQUID ETF",
            "SETF10GILT.NS": "Nifty 10 yr Benchmark G-Sec Index",
            "LIQUIDPLUS.NS": "Nifty 1D Rate Index",
            "LIQUIDBETF.NS": "Bajaj Finserv Nifty 1D Rate Liquid ETF",
            "LIQUID1.NS": "Kotak Nifty 1D Rate Liquid ETF",
            "HDFCLIQUID.NS": "HDFC Nifty 1D Rate Liquid ETF",
            "ABSLLIQUID.NS": "Aditya Birla Sun Life CRISIL Overnight Fund AI ETF",
            "LIQUIDIETF.NS": "S&P BSE Liquid Rate Index",
            "AXISCETF.NS": "NIFTY India Consumption Index",
            "LIQUID.NS": "Mirae Asset Nifty 1D Rate Liquid ETF",
            "LIQUIDSBI.NS": "SBI NIFTY 1D Rate ETF",
            "ABGSEC.NS": "Aditya Birla Sun Life CRISIL Broad Based Gilt ETF",
            "GSEC10ABSL.NS": "CRISIL 10 Year Gilt ETF",
            "LIQUIDBEES.NS": "Government Securities",
            "LIQUIDETF.NS": "Nifty1D rate index",
            "EBBETF0433.NS": "BHARAT Bond ETF-April 2033",
            "HDFCVALUE.NS": "HDFC NIFTY50 Value 20 ETF",
            "BBNPNBETF.NS": "Baroda BNP Paribas NIFTY Bank ETF",
            "EBBETF0431.NS": "Nifty BHARAT Bond",
            "EBBETF0430.NS": "Nifty BHARAT Bond",
            "SBIETFQLTY.NS": "Nifty 200 Quality 30 Index",
            "GOLDETF.NS": "Mirae Asset Gold ETF",
            "HDFCPVTBAN.NS": "HDFC NIFTY Private Bank ETF",
            "BBETF0432.NS": "Nifty BHARAT Bond Index - April 2032",
            "UTISENSETF.NS": "SENSEX",
            "EBBETF0425.NS": "Nifty BHARAT Bond",
            "GILT5YBEES.NS": "Nifty 5 yr Benchmark G-Sec Index",
            "NPBET.NS": "Nifty Private Bank Index",
            "SETFNIF50.NS": "Nifty 50",
            "LICNETFGSC.NS": "GSEC10 NSE Index",
            "BBNPPGOLD.NS": "Baroda BNP Paribas Gold ETF",
            "SETFNIFBK.NS": "Nifty Bank",
            "PVTBANIETF.NS": "Nifty Private Bank Index",
            "GOLDIETF.NS": "Gold",
            "AXISGOLD.NS": "Gold",
            "TATAGOLD.NS": "Tata Gold Exchange Traded Fund",
            "GOLDCASE.NS": "Zerodha Gold ETF",
            "CONSUMBEES.NS": "Nifty India Consumption TRI",
            "HDFCSENSEX.NS": "SENSEX",
            "NIFTY1.NS": "Nifty 50",
            "GROWWDEFNC.NS": "Nifty India Defence Index- Total Return Index",
            "BFSI.NS": "Nifty Financial Services Index",
            "BSLGOLDETF.NS": "Gold",
            "ABSLBANETF.NS": "Nifty Bank",
            "MSCIINDIA.NS": "MSCI India Index",
            "BANKBETF.NS": "Bajaj Finserv Nifty Bank ETF",
            "SHARIABEES.NS": "Shariah",
            "AXISBNKETF.NS": "Nifty Bank",
            "SDL26BEES.NS": "Nifty SDL Apr 2026 Top 20 Equal Weight Index",
            "SETFGOLD.NS": "Gold",
            "EGOLD.NS": "Edelweiss Gold ETF",
            "GROWWGOLD.NS": "Commodity",
            "BANKIETF.NS": "Nifty Bank",
            "BANKETFADD.NS": "DSP Nifty Bank ETF",
            "IVZINGOLD.NS": "Gold",
            "AXISILVER.NS": "Axis Silver ETF",
            "GOLDBEES.NS": "Gold",
            "BANKBEES.NS": "Nifty Bank",
            "METALIETF.NS": "Nifty Metal Index",
            "ALPHA.NS": "NIFTY Alpha 50 Index",
            "LICMFGOLD.NS": "Gold",
            "EMULTIMQ.NS": "Nifty500 Multicap Momentum Quality 50 Total Return Index",
            "HDFCNIFIT.NS": "HDFC NIFTY IT ETF",
            "GOLD1.NS": "Gold",
            "GOLDETFADD.NS": "DSP Gold ETF",
            "SBISILVER.NS": "SBI SILVER ETF",
            "HDFCGOLD.NS": "Gold",
            "HDFCQUAL.NS": "HDFC NIFTY100 Quality 30 ETF",
            "HDFCMOMENT.NS": "HDFC NIFTY200 Momentum 30 ETF",
            "HDFCNIFBAN.NS": "Nifty Bank",
            "SETFNN50.NS": "Nifty Next 50",
            "OILIETF.NS": "Nifty Oil & Gas Index",
            "BANKETF.NS": "Mirae Asset Nifty Bank ETF",
            "MOM100.NS": "Nifty Midcap 100",
            "ICICIB22.NS": "S&P BSE BHARAT 22 index",
            "LICNETFSEN.NS": "SENSEX",
            "NIFTYIETF.NS": "Nifty 50",
            "ECAPINSURE.NS": "BSE Capital Markets & Insurance Total Return Index",
            "TATSILV.NS": "Tata Silver Exchange Traded Fund",
            "MIDCAPIETF.NS": "Nifty Midcap 150",
            "QGOLDHALF.NS": "Gold",
            "ESILVER.NS": "Edelweiss Silver ETF",
            "GOLDSHARE.NS": "Gold",
            "METAL.NS": "Nifty Metal Total Return Index",
            "NIF100BEES.NS": "Nifty 100 TRI",
            "HEALTHY.NS": "Nifty Healthcare TRI",
            "NIFMID150.NS": "UTI Nifty Midcap 150 Exchange Traded Fund (ETF)",
            "CPSEETF.NS": "CPSE ETF",
            "HDFCSILVER.NS": "HDFC Silver ETF",
            "HDFCNIFTY.NS": "Nifty 50",
            "MNC.NS": "Kotak Nifty MNC ETF",
            "ABSLPSE.NS": "Aditya Birla Sun Life Nifty PSE ETF",
            "SBINEQWETF.NS": "Nifty50 Equal Weight",
            "BSLNIFTY.NS": "Nifty 50",
            "NIFTYBEES.NS": "Nifty 50",
            "FINIETF.NS": "ICICI Prudential Nifty Financial Services Ex-Bank ETF",
            "EQUAL50ADD.NS": "NIFTY 50 Equal Weight Index",
            "SILVERIETF.NS": "Domestic Price of Silver",
            "UTINEXT50.NS": "Nifty Next 50",
            "NV20.NS": "Nifty50 Value 20",
            "SILVRETF.NS": "Mirae Asset Silver ETF",
            "NEXT50IETF.NS": "Nifty Next 50",
            "IDFNIFTYET.NS": "Nifty 50",
            "SILVERADD.NS": "DSP Silver ETF",
            "BSLSENETFG.NS": "BSE SENSEX Index",
            "MOM30IETF.NS": "ICICI Prudential Nifty 200 Momentum 30 ETF",
            "SILVER.NS": "Physical price of Silver",
            "AXSENSEX.NS": "AXIS S&P BSE SENSEX ETF",
            "UTINIFTETF.NS": "Nifty 50",
            "MOREALTY.NS": "Motilal Oswal Nifty Realty ETF",
            "MID150CASE.NS": "Zerodha Nifty Midcap 150 ETF",
            "MONIFTY500.NS": "Motilal Oswal Nifty 500 ETF",
            "IVZINNIFTY.NS": "Nifty 50",
            "MIDQ50ADD.NS": "Nifty Midcap 150 Quality 50 Index",
            "EBANKNIFTY.NS": "Edelweiss Nifty Bank ETF",
            "SILVERBEES.NS": "Domestic price of Silver- based on LBMA Silver daily spot fixing price",
            "COMMOIETF.NS": "ICICI Prudential Nifty Commodities ETF",
            "HDFCBSE500.NS": "HDFC S&P BSE 500 ETF",
            "NIFTYETF.NS": "Nifty 50",
            "SILVERETF.NS": "UTI Silver Exchange Traded Fund (UTI Silver ETF)",
            "SILVER1.NS": "Kotak Silver ETF",
            "MOVALUE.NS": "Motilal Oswal S&P BSE Enhanced Value ETF",
            "TOP10ADD.NS": "Nifty Top 10 Equal Weight Index",
            "MID150BEES.NS": "Nifty Midcap 150 TRI",
            "NIFTYBETF.NS": "Bajaj Finserv Nifty 50 ETF",
            "LICNETFN50.NS": "Nifty 50",
            "MULTICAP.NS": "Nifty500 Multicap 50:25:25 Index",
            "UTIBANKETF.NS": "Nifty Bank",
            "PHARMABEES.NS": "Nifty Pharma TRI",
            "HDFCMID150.NS": "HDFC NIFTY Midcap 150 ETF",
            "AXISNIFTY.NS": "Nifty 50",
            "SENSEXIETF.NS": "SENSEX",
            "QNIFTY.NS": "Nifty 50",
            "HDFCSML250.NS": "HDFC NIFTY Smallcap 250 ETF",
            "MOSMALL250.NS": "Motilal Oswal Nifty Smallcap 250 ETF",
            "AXISHCETF.NS": "Nifty Healthcare Index",
            "MIDSELIETF.NS": "S&P BSE Midcap Select Index",
            "LOWVOLIETF.NS": "Nifty 100 Low Volatility 30 Index",
            "SENSEXETF.NS": "Mirae Asset S&P BSE Sensex ETF",
            "HDFCNEXT50.NS": "HDFC NIFTY NEXT 50 ETF",
            "MOMENTUM.NS": "Aditya Birla Sun Life Nifty 200 Momentum 30 ETF",
            "INFRABEES.NS": "Nifty Infra",
            "MOM50.NS": "Nifty 50",
            "ESG.NS": "NIFTY100 ESG SECTOR LEADERS",
            "PSUBNKBEES.NS": "Nifty PSU Bank",
            "MODEFENCE.NS": "Nifty India Defence Total Return Index",
            "HEALTHADD.NS": "DSP Nifty Healthcare ETF",
            "JUNIORBEES.NS": "Nifty Next 50",
            "GROWWEV.NS": "Nifty EV and New Age Automotive Index",
            "BSE500IETF.NS": "S&P BSE 500 index",
            "GROWWN200.NS": "Nifty 200 Index- Total Return Index",
            "MOQUALITY.NS": "Motilal Oswal S&P BSE Quality ETF",
            "MAHKTECH.NS": "Hang Seng TECH Total Return Index",
            "NIF100IETF.NS": "Nifty 100",
            "FMCGIETF.NS": "Nifty FMCG Index",
            "NIFITETF.NS": "UTI Nifty IT ETF",
            "NETF.NS": "Tata Nifty 50 Exchange Traded Fund",
            "NIFTYQLITY.NS": "Aditya Birla Sun Life Nifty 200 Quality 30 ETF",
            "MOLOWVOL.NS": "Nifty Midcap 100 TRI",
            "CONSUMER.NS": "Nifty India New Age Consumption",
            "MIDCAP.NS": "Nifty Midcap 50 Index",
            "NEXT30ADD.NS": "BSE SENSEX Next 30 Index",
            "MAKEINDIA.NS": "Nifty India Manufacturing Total Return Index",
            "PSUBANK.NS": "Nifty PSU Bank",
            "MIDSMALL.NS": "Mirae Asset Nifty MidSmallcap400 Momentum Quality 100 ETF",
            "LOWVOL.NS": "Mirae Asset Nifty 100 Low Volatility 30 ETF",
            "HEALTHIETF.NS": "Nifty Healthcare Index",
            "ALPL30IETF.NS": "Nifty Alpha Low-Volatility 30 Index",
            "MOHEALTH.NS": "Motilal Oswal S&P BSE Healthcare ETF",
            "MIDCAPETF.NS": "Mirae Asset Mutual Fund - Mirae Asset Nifty Midcap 150 ETF",
            "IT.NS": "NIFTY IT Index",
            "CONS.NS": "Kotak Nifty India Consumption ETF",
            "HDFCLOWVOL.NS": "HDFC NIFTY100 Low Volatility 30 ETF",
            "SMALLCAP.NS": "Mirae Asset Nifty Smallcap 250 Momentum Quality 100 ETF",
            "QUAL30IETF.NS": "ICICI Prudential Nifty 200 Quality 30 ETF",
            "HDFCGROWTH.NS": "HDFC NIFTY Growth Sectors 15 ETF",
            "DIVOPPBEES.NS": "Nifty Dividend Opportunities 50 TRI",
            "PSUBNKIETF.NS": "ICICI Prudential Nifty PSU Bank ETF",
            "AUTOBEES.NS": "Nifty Auto TRI",
            "VAL30IETF.NS": "Nifty200 Value 30 Index",
            "BANKPSU.NS": "Nifty PSU Bank Total Return Index",
            "MOMENTUM50.NS": "Nifty 500 Momentum 50 Total Return Index",
            "SBIETFCON.NS": "Nifty India Consumption Index",
            "NEXT50.NS": "Nifty Next 50",
            "EVINDIA.NS": "Nifty EV and New Age Automotive Total Return Index",
            "ALPHAETF.NS": "Mirae Asset Nifty 200 Alpha 30 ETF",
            "LOWVOL1.NS": "Kotak Nifty 100 Low Vol 30 ETF",
            "MOMOMENTUM.NS": "Nifty 200 Momentum 30 Total Return Index",
            "UTISXN50.NS": "BSE Sensex Next 50",
            "SBIETFIT.NS": "Nifty IT Index",
            "ABSLNN50ET.NS": "Nifty Next 50",
            "LICNFNHGP.NS": "Nifty 100",
            "PSUBANKADD.NS": "DSP Nifty PSU Bank ETF",
            "LICNMID100.NS": "LIC MF Nifty Midcap 100 ETF",
            "CONSUMIETF.NS": "Nifty India Consumption Index",
            "AUTOIETF.NS": "Nifty Auto Index",
            "ITIETF.NS": "Nifty IT Index",
            "TECH.NS": "Nifty IT TRI Index",
            "AXISTECETF.NS": "NIFTY IT Index",
            "ITBEES.NS": "Nifty IT TRI",
            "ITETF.NS": "Mirae Asset Nifty IT ETF",
            "TNIDETF.NS": "Nifty India Digital Index",
            "HNGSNGBEES.NS": "Hang Seng Index",
            "ITETFADD.NS": "DSP Nifty IT ETF",
            "GROWWRAIL.NS": "Nifty India Railways PSU Index",
            "MASPTOP50.NS": "S&P 500 Top 50 Total Return Index",
            "MAFANG.NS": "NYSE FANG+ Total Return Index",
            "MON100.NS": "Nasdaq100",
            "MONQ50.NS": "Nasdaq Q-50 Total Return Index",
  

            # "PIDILITIND.NS": "PIDILITIND - Stocks",
            # "PRINCEPIPE.NS": "Prince Pipes - Stocks",
            # "APOLLOPIPE.NS": "Apollo Pipes - Stocks",
            # "IRCTC.NS": "Irctc Stocks",
            # "MSUMI.NS": "Stocks",
            # "TANLA.NS": "Stocks",
            # "ASTRAL.NS": "Stocks",
            # "ROUTE.NS": "Stocks",
            # "SONACOMS.NS": "Stocks",
            # "APTUS.NS": "Stocks",
            # "RRKABEL.NS": "Stocks",
            # "AAVAS.NS": "Stocks",
            # "AETHER.NS": "Stocks",
            # "AFFLE.NS": "Stocks",
            # "ANGELONE.NS": "Stocks",
            # "APOLLOPIPE.NS": "Stocks",
            # "APTUS.NS": "Stocks",
            # "ASTRAL.NS": "Stocks",
            # "AVALON.NS": "Stocks",
            # "BAJFINANCE.NS": "Stocks",
            # "BERGEPAINT.NS": "Stocks",
            # "CLEAN.NS": "Stocks",
            # "COFORGE.NS": "Stocks",
            # "CYIENTDLM.NS": "Stocks",
            # "DATAPATTNS.NS": "Stocks",
            # "DEEPAKNTR.NS": "Stocks",
            # "DMART.NS": "Stocks",
            # "EASEMYTRIP.NS": "Stocks",
            # "EMIL.NS": "Stocks",
            # "ETHOSLTD.NS": "Stocks",
            # "EXIDEIND.NS": "Stocks",
            # "FCL.NS": "Stocks",
            # "FINEORG.NS": "Stocks",
            # "HAPPSTMNDS.NS": "Stocks",
            # "HARIOMPIPE.NS": "Stocks",
            # "HNDFDS.NS": "Stocks",
            # "HOMEFIRST.NS": "Stocks",
            # "IDEAFORGE.NS": "Stocks",
            # "INDIAMART.NS": "Stocks",
            # "INDIGOPNTS.NS": "Stocks",
            # "IREDA.NS": "Stocks",
            # "KAYNES.NS": "Stocks",
            # "KPIGREEN.NS": "Stocks",
            # "KSOLVES.NS": "Stocks",
            # "LTIM.NS": "Stocks",
            # "LTTS.NS": "Stocks",
            # "MANYAVAR.NS": "Stocks",
            # "MAPMYINDIA.NS": "Stocks",
            # "NAUKRI.NS": "Stocks",
            # "NEOGEN.NS": "Stocks",
            # "NETWEB.NS": "Stocks",
            # "OLECTRA.NS": "Stocks",
            # "PIIND.NS": "Stocks",
            # "POLYCAB.NS": "Stocks",
            # "PRINCEPIPE.NS": "Stocks",
            # "PRUDENT.NS": "Stocks",
            # "SIGACHI.NS": "Stocks",
            # "SIGMA.NS": "Stocks",
            # "SIRCA.NS": "Stocks",
            # "SONACOMS.NS": "Stocks",
            # "SRF.NS": "Stocks",
            # "TATAELXSI.NS": "Stocks",
            # "TITAN.NS": "Stocks",
            # "VBL.NS": "Stocks",
            # "VENUSPIPES.NS": "Stocks",
            # "VINATIORGA.NS": "Stocks",
            # "YASHO.NS": "Stocks",
            # "WAAREERTL.BO" : "Stocks",
            # "IRFC.BO": "Stocks",
            # "TATAMOTORS.BO": "Stocks",
        }