class Tickers:
       ticker_json =  {
            "0P0000XW51.BO": "Quant ELSS Tax Saver Fund MF",
            "0P00017844.BO": "Mirae Asset ELSS Tax Saver Fund MF",
            "0P00005VCS.BO": "HSBC ELSS Tax Saver Fund MF",
            "0P0000XVU7.BO": "Axis ELSS Tax Saver Fund MF",
            "0P0000XV1I.BO": "Bandhan ELSS Tax Saver Fund MF",
            "0P0001R64W.BO": "Motilal Oswal Nifty Microcap 250 Index Fund MF",
            "0P0000XVDP.BO": "Nippon India Growth Direct Growth MF",
            "0P0001RQX5.BO": "Zerodha Nifty LargeMidcap 250 Index Fund Tax Saver Dir Gr MF",
            "0P0000GB29.BO": "Aditya BSL ELSS Tax Saver Gr MF",
            "0P0000XW04.BO": "Canara Robeco ELSS Tax Saver Dir Gr MF",
            "0P00011MAX.BO": "Axis Small Cap Fund Dir Gr MF",
            "0P000159Q2.BO": "Motilal Oswal ELSS Tax Saver Reg Gr MF",
            "0P00009J3K.BO": "HDFC Mid-Cap Opportunities Gr MF",
            "0P0000XVFY.BO": "Nippon India Small Cap Dir Gr MF",
            "0P00008TPO.BO": "Kotak Emerging Equity Scheme MF",
            "0P0000KV39.BO": "SBI Small Cap Fund Reg Gr MF",
            "0P0000XVUH.BO": "Axis Midcap Fund Dir Gr MF",
            "0P00012ALU.BO": "Motilal Oswal Midcap Reg Gr MF",
            
            "MAFANG.NS": "NYSE FANG+ Total Return Index ETF",
            "MON100.NS": "Nasdaq100 ETF",
            "MONQ50.NS": "Nasdaq Q-50 Total Return Index ETF",
            "MASPTOP50.NS": "S&P 500 Top 50 Total Return Index ETF",
            "HNGSNGBEES.NS": "Hang Seng Index ETF",
            "HEALTHIETF.NS": "Nifty Healthcare Index ETF",
            "MAHKTECH.NS": "Hang Seng TECH Total Return Index ETF",
            "HEALTHADD.NS": "DSP Nifty Healthcare ETF ETF",
            "AXISHCETF.NS": "Nifty Healthcare Index ETF ETF",
            "HEALTHY.NS": "Nifty Healthcare TRI ETF",
            "PHARMABEES.NS": "Nifty Pharma TRI ETF",
            "MOREALTY.NS": "Motilal Oswal Nifty Realty ETF ETF",
            "MODEFENCE.NS": "Nifty India Defence Total Return Index ETF",
            "MOHEALTH.NS": "Motilal Oswal S&P BSE Healthcare ETF ETF",
            "GROWWDEFNC.NS": "Nifty India Defence Index- Total Return Index ETF",
            "MIDSELIETF.NS": "S&P BSE Midcap Select Index ETF",
            "LICNMID100.NS": "LIC MF Nifty Midcap 100 ETF ETF",
            "ALPHA.NS": "NIFTY Alpha 50 Index ETF",
            "LICNETFSEN.NS": "SENSEX ETF",
            "GSEC10YEAR.NS": "Mirae Asset Nifty 8-13 yr G-Sec ETF ETF",
            "HDFCSML250.NS": "HDFC NIFTY Smallcap 250 ETF ETF",
            "MOM100.NS": "Nifty Midcap 100 ETF",
            "MID150CASE.NS": "Zerodha Nifty Midcap 150 ETF ETF",
            "MIDCAPIETF.NS": "Nifty Midcap 150 ETF",
            "SMALLCAP.NS": "Mirae Asset Nifty Smallcap 250 Momentum Quality 100 ETF ETF",
            "MIDCAPETF.NS": "Mirae Asset Mutual Fund - Mirae Asset Nifty Midcap 150 ETF ETF",
            "NIF10GETF.NS": "UTI Nifty 10 yr Benchmark G-Sec ETF ETF",
            "HDFCMID150.NS": "HDFC NIFTY Midcap 150 ETF ETF",
            "MID150BEES.NS": "Nifty Midcap 150 TRI ETF",
            "AXISGOLD.NS": "Gold ETF",
            "TNIDETF.NS": "Nifty India Digital Index ETF",
            "MIDCAP.NS": "Nifty Midcap 50 Index ETF",
            "MIDSMALL.NS": "Mirae Asset Nifty MidSmallcap400 Momentum Quality 100 ETF ETF",
            "BBNPPGOLD.NS": "Baroda BNP Paribas Gold ETF ETF",
            "NIFMID150.NS": "UTI Nifty Midcap 150 Exchange Traded Fund (ETF) ETF",
            "GOLD1.NS": "Gold ETF",
            "MOSMALL250.NS": "Motilal Oswal Nifty Smallcap 250 ETF ETF",
            "IVZINGOLD.NS": "Gold ETF",
            "GROWWGOLD.NS": "Commodity ETF",
            "SETFGOLD.NS": "Gold ETF",
            "QGOLDHALF.NS": "Gold ETF",
            "GOLDBEES.NS": "Gold ETF",
            "GOLDETFADD.NS": "DSP Gold ETF ETF",
            "ALPHAETF.NS": "Mirae Asset Nifty 200 Alpha 30 ETF ETF",
            "TATAGOLD.NS": "Tata Gold Exchange Traded Fund ETF",
            "GOLDIETF.NS": "Gold ETF",
            "LICMFGOLD.NS": "Gold ETF",
            "GOLDSHARE.NS": "Gold ETF",
            "LICNETFGSC.NS": "GSEC10 NSE Index ETF",
            "GOLDCASE.NS": "Zerodha Gold ETF ETF",
            "HDFCGOLD.NS": "Gold ETF",
            "GOLDETF.NS": "Mirae Asset Gold ETF ETF",
            "EGOLD.NS": "Edelweiss Gold ETF ETF",
            "BSLGOLDETF.NS": "Gold ETF",
            "MOGSEC.NS": "Nifty 5 yr Benchmark G-Sec Index ETF",
            "SDL26BEES.NS": "Nifty SDL Apr 2026 Top 20 Equal Weight Index ETF",
            "EBBETF0425.NS": "Nifty BHARAT Bond ETF",
            "HDFCBSE500.NS": "HDFC S&P BSE 500 ETF ETF",
            "EBBETF0433.NS": "BHARAT Bond ETF-April 2033 ETF",
            "EBBETF0431.NS": "Nifty BHARAT Bond ETF",
            "GSEC5IETF.NS": "Nifty 5 yr Benchmark G-Sec Index ETF",
            "AXISBPSETF.NS": "Nifty AAA Bond Plus SDL Apr 2026 50:50 Index ETF",
            "GSEC10IETF.NS": "ICICI Prudential Nifty 10 yr Benchmark G-Sec ETF ETF",
            "EBBETF0430.NS": "Nifty BHARAT Bond ETF",
            "MOMENTUM50.NS": "Nifty 500 Momentum 50 Total Return Index ETF",
            "MONIFTY500.NS": "Motilal Oswal Nifty 500 ETF ETF",
            "BBETF0432.NS": "Nifty BHARAT Bond Index - April 2032 ETF",
            "MULTICAP.NS": "Nifty500 Multicap 50:25:25 Index ETF",
            "AXISCETF.NS": "NIFTY India Consumption Index ETF",
            "NIF5GETF.NS": "UTI Nifty 5 yr Benchmark G-Sec ETF ETF",
            "EMULTIMQ.NS": "Nifty500 Multicap Momentum Quality 50 Total Return Index ETF",
            "MIDQ50ADD.NS": "Nifty Midcap 150 Quality 50 Index ETF",
            "CONSUMBEES.NS": "Nifty India Consumption TRI ETF",
            "SILVERADD.NS": "DSP Silver ETF ETF",
            "TECH.NS": "Nifty IT TRI Index ETF",
            "CONSUMIETF.NS": "Nifty India Consumption Index ETF",
            "UTISXN50.NS": "BSE Sensex Next 50 ETF",
            "AXISILVER.NS": "Axis Silver ETF ETF",
            "FINIETF.NS": "ICICI Prudential Nifty Financial Services Ex-Bank ETF ETF",
            "SILVRETF.NS": "Mirae Asset Silver ETF ETF",
            "SILVER1.NS": "Kotak Silver ETF ETF",
            "SBIETFCON.NS": "Nifty India Consumption Index ETF",
            "SILVER.NS": "Physical price of Silver ETF",
            "SILVERETF.NS": "UTI Silver Exchange Traded Fund (UTI Silver ETF) ETF",
            "HDFCSILVER.NS": "HDFC Silver ETF ETF",
            "TATSILV.NS": "Tata Silver Exchange Traded Fund ETF",
            "SILVERBEES.NS": "Domestic price of Silver- based on LBMA Silver daily spot fixing price ETF",
            "ITETFADD.NS": "DSP Nifty IT ETF ETF",
            "SILVERIETF.NS": "Domestic Price of Silver ETF",
            "ESILVER.NS": "Edelweiss Silver ETF ETF",
            "SBISILVER.NS": "SBI SILVER ETF ETF",
            "SBIETFIT.NS": "Nifty IT Index ETF",
            "SHARIABEES.NS": "Shariah ETF",
            "HDFCGROWTH.NS": "HDFC NIFTY Growth Sectors 15 ETF ETF",
            "UTINEXT50.NS": "Nifty Next 50 ETF",
            "MAKEINDIA.NS": "Nifty India Manufacturing Total Return Index ETF",
            "ITIETF.NS": "Nifty IT Index ETF",
            "ITETF.NS": "Mirae Asset Nifty IT ETF ETF",
            "LOWVOLIETF.NS": "Nifty 100 Low Volatility 30 Index ETF",
            "IT.NS": "NIFTY IT Index ETF",
            "MOLOWVOL.NS": "Nifty Midcap 100 TRI ETF",
            "ALPL30IETF.NS": "Nifty Alpha Low-Volatility 30 Index ETF",
            "BFSI.NS": "Nifty Financial Services Index ETF",
            "BSE500IETF.NS": "S&P BSE 500 index ETF",
            "HDFCLOWVOL.NS": "HDFC NIFTY100 Low Volatility 30 ETF ETF",
            "HDFCNIFIT.NS": "HDFC NIFTY IT ETF ETF",
            "AXISTECETF.NS": "NIFTY IT Index ETF",
            "CONS.NS": "Kotak Nifty India Consumption ETF ETF",
            "AXISNIFTY.NS": "Nifty 50 ETF",
            "LOWVOL1.NS": "Kotak Nifty 100 Low Vol 30 ETF ETF",
            "NIFITETF.NS": "UTI Nifty IT ETF ETF",
            "MOM30IETF.NS": "ICICI Prudential Nifty 200 Momentum 30 ETF ETF",
            "BBNPNBETF.NS": "Baroda BNP Paribas NIFTY Bank ETF ETF",
            "LOWVOL.NS": "Mirae Asset Nifty 100 Low Volatility 30 ETF ETF",
            "ITBEES.NS": "Nifty IT TRI ETF",
            "MOMOMENTUM.NS": "Nifty 200 Momentum 30 Total Return Index ETF",
            "NEXT50.NS": "Nifty Next 50 ETF",
            "MOQUALITY.NS": "Motilal Oswal S&P BSE Quality ETF ETF",
            "ABSLNN50ET.NS": "Nifty Next 50 ETF",
            "TOP100CASE.NS": "Zerodha Nifty 100 ETF ETF",
            "SENSEXIETF.NS": "SENSEX ETF",
            "NEXT50IETF.NS": "Nifty Next 50 ETF",
            "JUNIORBEES.NS": "Nifty Next 50 ETF",
            "EBANKNIFTY.NS": "Edelweiss Nifty Bank ETF ETF",
            "HDFCNEXT50.NS": "HDFC NIFTY NEXT 50 ETF ETF",
            "HDFCNIF100.NS": "HDFC NIFTY 100 ETF ETF",
            "AUTOBEES.NS": "Nifty Auto TRI ETF",
            "HDFCMOMENT.NS": "HDFC NIFTY200 Momentum 30 ETF ETF",
            "NIF100BEES.NS": "Nifty 100 TRI ETF",
            "MOMENTUM.NS": "Aditya Birla Sun Life Nifty 200 Momentum 30 ETF ETF",
            "LICNETFN50.NS": "Nifty 50 ETF",
            "AUTOIETF.NS": "Nifty Auto Index ETF",
            "NIF100IETF.NS": "Nifty 100 ETF",
            "SENSEXADD.NS": "DSP S&P BSE Sensex ETF ETF",
            "ESG.NS": "NIFTY100 ESG SECTOR LEADERS ETF",
            "BANKNIFTY1.NS": "Nifty Bank ETF",
            "SETFNIFBK.NS": "Nifty Bank ETF",
            "BANKBEES.NS": "Nifty Bank ETF",
            "BANKIETF.NS": "Nifty Bank ETF",
            "MOM50.NS": "Nifty 50 ETF",
            "SETFNIF50.NS": "Nifty 50 ETF",
            "NIFTY1.NS": "Nifty 50 ETF",
            "UTINIFTETF.NS": "Nifty 50 ETF",
            "SETFNN50.NS": "Nifty Next 50 ETF",
            "NIFTYBEES.NS": "Nifty 50 ETF",
            "SENSEXETF.NS": "Mirae Asset S&P BSE Sensex ETF ETF",
            "LICNFNHGP.NS": "Nifty 100 ETF",
            "NIFTYETF.NS": "Nifty 50 ETF",
            "NIFTYIETF.NS": "Nifty 50 ETF",
            "HDFCNIFBAN.NS": "Nifty Bank ETF",
            "HDFCNIFTY.NS": "Nifty 50 ETF",
            "NETF.NS": "Tata Nifty 50 Exchange Traded Fund ETF",
            "HDFCPVTBAN.NS": "HDFC NIFTY Private Bank ETF ETF",
            "ABSLBANETF.NS": "Nifty Bank ETF",
            "HDFCSENSEX.NS": "SENSEX ETF",
            "QNIFTY.NS": "Nifty 50 ETF",
            "BSLNIFTY.NS": "Nifty 50 ETF",
            "BANKETF.NS": "Mirae Asset Nifty Bank ETF ETF",
            "NPBET.NS": "Nifty Private Bank Index ETF",
            "BSLSENETFG.NS": "BSE SENSEX Index ETF",
            "TOP10ADD.NS": "Nifty Top 10 Equal Weight Index ETF",
            "IDFNIFTYET.NS": "Nifty 50 ETF",
            "EQUAL50ADD.NS": "NIFTY 50 Equal Weight Index ETF",
            "IVZINNIFTY.NS": "Nifty 50 ETF",
            "SBINEQWETF.NS": "Nifty50 Equal Weight ETF",
            "NIFTYBETF.NS": "Bajaj Finserv Nifty 50 ETF ETF",
            "METALIETF.NS": "Nifty Metal Index ETF",
            "METAL.NS": "Nifty Metal Total Return Index ETF",
            "BANKBETF.NS": "Bajaj Finserv Nifty Bank ETF ETF",
            "AXISBNKETF.NS": "Nifty Bank ETF",
            "PVTBANIETF.NS": "Nifty Private Bank Index ETF",
            "AXSENSEX.NS": "AXIS S&P BSE SENSEX ETF ETF",
            "NIFTY50ADD.NS": "Nifty 50 Index ETF",
            "INFRAIETF.NS": "ICICI Prudential Nifty Infrastructure ETF ETF",
            "UTIBANKETF.NS": "Nifty Bank ETF",
            "GROWWEV.NS": "Nifty EV and New Age Automotive Index ETF",
            "PVTBANKADD.NS": "DSP Nifty Private Bank ETF ETF",
            "BANKETFADD.NS": "DSP Nifty Bank ETF ETF",
            "UTISENSETF.NS": "SENSEX ETF",
            "COMMOIETF.NS": "ICICI Prudential Nifty Commodities ETF ETF",
            "INFRABEES.NS": "Nifty Infra ETF",
            "HDFCVALUE.NS": "HDFC NIFTY50 Value 20 ETF ETF",
            "SBIETFPB.NS": "Nifty Private Bank Index ETF",
            "EVINDIA.NS": "Nifty EV and New Age Automotive Total Return Index ETF",
            "NV20.NS": "Nifty50 Value 20 ETF",
            "OILIETF.NS": "Nifty Oil & Gas Index ETF",
            "NV20IETF.NS": "Nifty50 Value 20 ETF",
            "NV20BEES.NS": "Nifty50 Value20 TRI ETF",
            "FMCGIETF.NS": "Nifty FMCG Index ETF",
            "MNC.NS": "Kotak Nifty MNC ETF ETF",
            "MOVALUE.NS": "Motilal Oswal S&P BSE Enhanced Value ETF ETF",
            "DIVOPPBEES.NS": "Nifty Dividend Opportunities 50 TRI ETF",
            "PSUBNKBEES.NS": "Nifty PSU Bank ETF",
            "BANKPSU.NS": "Nifty PSU Bank Total Return Index ETF",
            "HDFCPSUBK.NS": "HDFC NIFTY PSU BANK ETF ETF",
            "NIFTYQLITY.NS": "Aditya Birla Sun Life Nifty 200 Quality 30 ETF ETF",
            "PSUBANK.NS": "Nifty PSU Bank ETF",
            "PSUBNKIETF.NS": "ICICI Prudential Nifty PSU Bank ETF ETF",
            "QUAL30IETF.NS": "ICICI Prudential Nifty 200 Quality 30 ETF ETF",
            "SBIETFQLTY.NS": "Nifty 200 Quality 30 Index ETF",
            "HDFCQUAL.NS": "HDFC NIFTY100 Quality 30 ETF ETF",
            "VAL30IETF.NS": "Nifty200 Value 30 Index ETF",
            "ICICIB22.NS": "S&P BSE BHARAT 22 index ETF",
            "ABSLPSE.NS": "Aditya Birla Sun Life Nifty PSE ETF ETF",
            "CPSEETF.NS": "CPSE ETF ETF",

            
            "PRINCEPIPE.NS": "Prince Pipes - Stocks",
            "APOLLOPIPE.NS": "Apollo Pipes - Stocks",
            "IRCTC.NS": "Irctc Stocks",
            "MSUMI.NS": "Stocks",
            "TANLA.NS": "Stocks",
            "ASTRAL.NS": "Stocks",
            "ROUTE.NS": "Stocks",
            "SONACOMS.NS": "Stocks",
            "APTUS.NS": "Stocks",
            "RRKABEL.NS": "Stocks",
            "AAVAS.NS": "Stocks",
            "AETHER.NS": "Stocks",
            "AFFLE.NS": "Stocks",
            "ANGELONE.NS": "Stocks",
            "APOLLOPIPE.NS": "Stocks",
            "APTUS.NS": "Stocks",
            "ASTRAL.NS": "Stocks",
            "AVALON.NS": "Stocks",
            "BAJFINANCE.NS": "Stocks",
            "BERGEPAINT.NS": "Stocks",
            "CLEAN.NS": "Stocks",
            "COFORGE.NS": "Stocks",
            "CYIENTDLM.NS": "Stocks",
            "DATAPATTNS.NS": "Stocks",
            "DEEPAKNTR.NS": "Stocks",
            "DMART.NS": "Stocks",
            "EASEMYTRIP.NS": "Stocks",
            "EMIL.NS": "Stocks",
            "ETHOSLTD.NS": "Stocks",
            "EXIDEIND.NS": "Stocks",
            "FCL.NS": "Stocks",
            "FINEORG.NS": "Stocks",
            "HAPPSTMNDS.NS": "Stocks",
            "HARIOMPIPE.NS": "Stocks",
            "HNDFDS.NS": "Stocks",
            "HOMEFIRST.NS": "Stocks",
            "IDEAFORGE.NS": "Stocks",
            "INDIAMART.NS": "Stocks",
            "INDIGOPNTS.NS": "Stocks",
            "IREDA.NS": "Stocks",
            "KAYNES.NS": "Stocks",
            "KPIGREEN.NS": "Stocks",
            "KSOLVES.NS": "Stocks",
            "LTIM.NS": "Stocks",
            "LTTS.NS": "Stocks",
            "MANYAVAR.NS": "Stocks",
            "MAPMYINDIA.NS": "Stocks",
            "NAUKRI.NS": "Stocks",
            "NEOGEN.NS": "Stocks",
            "NETWEB.NS": "Stocks",
            "OLECTRA.NS": "Stocks",
            "PIIND.NS": "Stocks",
            "POLYCAB.NS": "Stocks",
            "PRINCEPIPE.NS": "Stocks",
            "PRUDENT.NS": "Stocks",
            "SIGACHI.NS": "Stocks",
            "SIGMA.NS": "Stocks",
            "SIRCA.NS": "Stocks",
            "SONACOMS.NS": "Stocks",
            "SRF.NS": "Stocks",
            "TATAELXSI.NS": "Stocks",
            "TITAN.NS": "Stocks",
            "VBL.NS": "Stocks",
            "VENUSPIPES.NS": "Stocks",
            "VINATIORGA.NS": "Stocks",
            "YASHO.NS": "Stocks"
        }